version: 2
updates:
  - package-ecosystem: npm
    directory: "/packages/dashboard"
    schedule:
      interval: monthly
 - package-ecosystem: docker
    directory: "/docker/sia"
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: "/packages/dashboard"
    schedule:
      interval: monthly
