name: Deploy website to Skynet

on:
  push:
    branches:
      - website

defaults:
  run:
    working-directory: packages/website

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Install dependencies
        run: npm i --force

      - name: "Build website"
        run: npm run build

      - name: "Integration tests"
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          working-directory: packages/website
          install-command: npm i --force --silent
          record: true
          start: npm run serve
          wait-on: "http://127.0.0.1:9000"

      - name: "Deploy to Skynet"
        uses: kwypchlo/deploy-to-skynet-action@main
        with:
          upload-dir: public
          github-token: ${{ secrets.GITHUB_TOKEN }}
          registry-seed: ${{ github.event_name == 'push' && github.ref == 'refs/heads/website' && secrets.WEBSITE_REGISTRY_SEED || '' }}
