name: Lint - packages/handshake-api

on:
  pull_request:
    paths:
      - packages/handshake-api/**

defaults:
  run:
    working-directory: packages/handshake-api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: yarn
      - run: yarn prettier --check .
