name: Static Code Analysis

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pacakge: [dashboard, dnslink-api, handshake-api, health-check, website]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Static code analysis for ${{ matrix.package }}
        working-directory: packages/${{ matrix.package }}
        run: yarn && yarn prettier --check .
